require("./models/init")
require("./router/init")
//require("./Mock/mockAccount")
// require("./Mock/mockUsers")
// require("./Mock/mockTag")
// require("./Mock/mockArticle")
// require("./Mock/mockCollect")
// require("./Mock/mockFollow")
// require("./Mock/mockHistory")